  - name: Modify Keystone Configuration
    ini_file:
      dest: /etc/keystone/keystone.conf
      section: database
      option: connection
      value: mysql://root:swiftstack@localhost/keystone
      backup: yes
    register: option_db

  - name: Modify Keystone paste INI
    ini_file:
      dest: /etc/keystone/keystone-paste.ini
      section: pipeline:public_api
      option: pipeline
      value: sizelimit url_normalize build_auth_context token_auth admin_token_auth xml_body_v2 json_body ec2_extension s3_extension user_crud_extension public_service
      mode: 0644
      backup: yes
    register: option_pipeline

  - name: Enable Keystone Logs
    ini_file:
      dest: /etc/keystone/keystone.conf
      section: DEFAULT
      option: debug
      value: true
      backup: yes
    register: option_log1

  - name: Enable Verbose Logs
    ini_file:
      dest: /etc/keystone/keystone.conf
      section: DEFAULT
      option: verbose
      value: true
      backup: yes
    register: option_log2   

  - name: Change Log Files
    ini_file:
      dest: /etc/keystone/keystone.conf
      section: DEFAULT
      option: log_file
      value: keystone.log
      backup: yes
    register: option_logfile


###
# To refine this task by changing it as handler instead of a task. 
# Then notify the handler if above tasks are changed 
###
  - name: Restart Keystone Server
    service:
      name: keystone
      state: restarted
    when: 
      - option_db.changed or
        option_pipeline.changed or 
        option_log1.changed or 
        option_log2.changed or 
        option_logfile.changed 
