---

# To install and start Keystone server
# This playbook is for Kilo release
# Author : Hugo Kuo <hugo@swiftstack.com>

  - name: Add Kilo Cloud Archive repo
    apt_repository:
      repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main

  - name: Install Keystone package
    apt: 
      name: keystone
      state: latest
      update_cache: yes
      allow_unauthenticated: yes

  - include: mysql.yaml

  - include: keystone_conf.yaml

  - name: Checking Tables of Keystone DB
    shell: mysql -uroot -pswiftstack keystone -e "SHOW TABLES LIKE 'domain'" | grep domain
    changed_when: table_exist == "" 
    ignore_errors: yes
    register: table_exist

  - name: Populate initial Keystone DB tables
    command: keystone-manage db_sync 
    when: 
      - table_exist.stdout == ""
