---

# To install and start Keystone server
# This playbook is for Kilo release
# Author : Hugo Kuo <hugo@swiftstack.com>

  - name: Add Kilo Cloud Archive repo
    apt_repository:
      repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main

  - name: Install Keystone package
    apt: 
      name: keystone
      state: latest
      update_cache: yes
      allow_unauthenticated: yes

  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
  - name: Start the MySQL service
    sudo: yes
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    sudo: yes
    vars:
      mysql_root_password: swiftstack
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 

  - name: Create a new database with name 'keystone'
    mysql_db:
      name: keystone
      state: present
      login_password: swiftstack
      login_user: root
